<a href="https://colab.research.google.com/github/NidhiChaurasia/Data-Science-Projects/blob/main/IRISClasssification_Using_K_Nearest_Neighbor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sklearn

##Building an ML model to predict different species of IRIS Flower

#About the Dataset

The dataset we use for this example is the iris dataset http://archive.ics.uci.edu/ml/datasets/Iris ,a classical dataset in machine learning and statistics.It is included in scikit-learn in the dataset module.We can load it by calling the load_iris function or import it from the device in csv format after downloading from UCI machine learning Repository.

In [23]:
from sklearn.datasets import load_iris
flower = load_iris()

The iris object that is returned by load_iris is a Bunch object,which is very similar to a dictionary.It contains keys and values.

In [24]:
flower.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

#Description of Dataset IRIS

In [25]:
print(flower['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

The feature_names are a list of strings,giving the description of each feature

##Analyzing the Data

In [30]:
flower['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [31]:
flower['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [32]:
type(flower['data'])

numpy.ndarray

In [33]:
flower['data'].shape

(150, 4)

Here are the feature values for the first ten samples:

In [35]:
flower['data'][:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [36]:
flower['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

The meaning of the numbers are given by the iris['target_names']array:0 means Setosa,1 means Versicolor and 2 means Virginica.

##**Training the ML Model and testing dataset**

The part of the data that is used to build our machine learning model,is called the training set.The rest of the data will be used to access how well the model works and is called test data,test set or hold-out set.

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(flower['data'],flower['target'],
random_state=0)

The output of the train_test_split function are X_train,X_test,y_train and y_test, which are all numpy arrays.X_train contains 75% of the rows of the dataset,and X_test contains the remaining 25%.

In [38]:
X_train.shape

(112, 4)

In [39]:
X_test.shape

(38, 4)

##Using K-Nearest Neighbor for Classification

In [40]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [41]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [42]:
import numpy as np
X_new = np.array([[5,2.9,1,0.2]])
X_new.shape

(1, 4)

In [43]:
prediction = knn.predict(X_new)
prediction

array([0])

In [45]:
flower['target_names'][prediction]

array(['setosa'], dtype='<U10')

##**Assessing the** **model**

We can also use the score method of the knn object,which will compute the test set accuracy for us.

In [46]:
knn.score(X_test,y_test)

0.9736842105263158